import { Lora, Assistant } from "next/font/google";
import "./globals.css";  
import { AuthProvider } from "./contexts/AuthContext";

const lora = Lora({
  variable: "--font-lora",  
  subsets: ["latin"],  
});

const assistant = Assistant({
  weight: ["400", "700"], 
  subsets: ["latin"],
  variable: "--font-assistant", 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lora.variable} ${assistant.variable} antialiased`} 
      >
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}

